dist: xenial
language: python
python:
  - "3.7"
  - "3.6"

cache:
  directories:
    - $HOME/.pip-cache/

# ignore the virtualenv that Travis creates
# setup a secure login to CodeCov
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - secure: 2c0250fb-dfb1-45c9-abaf-cd3d874326c5

# install mdl for checking Markdown
before_install:
  - gem install mdl

notifications:
  email: never

# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install --upgrade pipenv
  - pipenv install --dev

# perform testing:
# --> run the test suite with pytest and codecov
# --> Check for black format
# --> lint the functions with flake8
# --> lint the test suites with flake8
# --> lint the functions with pylint
# --> lint the test suites with pylint
# --> lint the README documentation with mdl
script:
  - shopt -s globstar
  - pipenv run pytest tests --cov-config pytest.cov --cov
  - pipenv run black **/*.py --check
  - pipenv run flake8 **/*.py
  - pipenv run pylint **/*.py
  - mdl README.md

# report coverage information to CodeCov
after_success:
  - pipenv run codecov
